# tf.errors.AlreadyExistsError

View source on GitHub  Raised when an entity that we attempted to create
already exists. Inherits From: `OpError`

#### View aliases

Compat aliases for migration See Migration guide for more details.
`tf.compat.v1.errors.AlreadyExistsError`

    
    tf.errors.AlreadyExistsError(
        node_def, op, message
    )
    
For example, running an operation that saves a file (e.g. `tf.train.Saver.save`) could potentially raise this exception if an explicit filename for an existing file was passed. | Attributes  
---  
`error_code` |  The integer error code that describes the error.   
`message` |  The error message that describes the error.   
`node_def` |  The `NodeDef` proto representing the op that failed.   
`op` |  The operation that failed, if known. 
> Note: If the failed op was synthesized at runtime, e.g. a `Send` or `Recv`
> op, there will be no corresponding `tf.Operation` object. In that case, this
> will return `None`, and you should instead use the
> `tf.errors.OpError.node_def` to discover information about the op.  
Â© 2020 The TensorFlow Authors. All rights reserved.  
Licensed under the Creative Commons Attribution License 3.0.  
Code samples licensed under the Apache 2.0 License.  
https://www.tensorflow.org/versions/r2.4/api_docs/python/tf/errors/AlreadyExistsError

  *[ISP]: Internet Service Provider
  *[LIFO]: last-in, first-out
  *[FIFO]: first-in, first-out

