<h1>pandas.errors.UnsupportedFunctionCall</h1> <dl class="py exception"> <dt class="sig sig-object py" id="pandas.errors.UnsupportedFunctionCall"> <em class="property"><span class="pre">exception</span></em><span class="sig-prename descclassname"><span class="pre">pandas.errors.</span></span><span class="sig-name descname"><span class="pre">UnsupportedFunctionCall</span></span><a class="reference external" href="https://github.com/pandas-dev/pandas/blob/v1.4.0/pandas/errors/__init__.py#L38-L43"><span class="viewcode-link"><span class="pre">[source]</span></span></a>
</dt> <dd>
<p>Exception raised when attempting to call a numpy function on a pandas object, but that function is not supported by the object e.g. <code class="docutils literal notranslate"><span class="pre">np.cumsum(groupby_object)</span></code>.</p> </dd>
</dl><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2008&ndash;2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team<br>Licensed under the 3-clause BSD License.<br>
    <a href="https://pandas.pydata.org/pandas-docs/version/1.4.0/reference/api/pandas.errors.UnsupportedFunctionCall.html" class="_attribution-link">https://pandas.pydata.org/pandas-docs/version/1.4.0/reference/api/pandas.errors.UnsupportedFunctionCall.html</a>
  </p>
</div>
