# pandas.errors.UnsupportedFunctionCall

exceptionpandas.errors.UnsupportedFunctionCall[source]

    
Exception raised when attempting to call a numpy function on a pandas object,
but that function is not supported by the object e.g.
`np.cumsum(groupby_object)`.

© 2008–2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData
Development Team  
Licensed under the 3-clause BSD License.  
https://pandas.pydata.org/pandas-
docs/version/1.4.0/reference/api/pandas.errors.UnsupportedFunctionCall.html

